version: "3.8"

services:

  front-end:
    container_name: expense-tracker-frontend
    image: expense-tracker:frontend
    ports: 
      - '3000:3000'
  psql-db:
    image: postgres
    container_name: psql-db
    restart: always
    environment:
      - POSTGRES_DB=expenses
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER = postgres
    ports:
      - '5432:5432'

  back_end:
    container_name: expense-tracker
    image: expense-tracker:backend
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/expenses
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - psql-db
